name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions:
      contents: write
    env:
      llvm_repo_url: https://github.com/llvm/llvm-project.git
      llvm_branch: release/22.x

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download LLVM
        uses: robinraju/release-downloader@v1
        with:
          repository: 'llvm/llvm-project'
          tag: 'llvmorg-22.1.3'
          fileName: 'clang+llvm-22.1.3-x86_64-pc-windows-msvc.tar.xz'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: pwsh
        run: |
          7z x clang+llvm-22.1.3-x86_64-pc-windows-msvc.tar.xz
          7z x clang+llvm-22.1.3-x86_64-pc-windows-msvc.tar
          $LLVM_BOOTSTRAP_PATH = "$pwd\clang+llvm-22.1.3-x86_64-pc-windows-msvc"
          ./build.ps1 "${{ env.llvm_repo_url }}" "${{ env.llvm_branch }}" "$LLVM_BOOTSTRAP_PATH"

      - name: Zip
        shell: pwsh
        env:
          DWARFS_VERSION: 0.15.3
          MKDWARFS_OPTIONS: "--categorize binary --chmod=ugo=rx"
        run: |
          New-Item -Path "release" -Force -ItemType "directory"
          Invoke-WebRequest https://github.com/mhx/dwarfs/releases/download/v${{ env.DWARFS_VERSION }}/dwarfs-universal-${{ env.DWARFS_VERSION }}-Windows-AMD64.exe -Out .\dwarfs-universal.exe
          .\dwarfs-universal.exe --tool=mkdwarfs -i llvm-project/build/install -o release/llvm.dwarfs ${{ env.MKDWARFS_OPTIONS }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.llvm_branch }}
          tag_name: ${{ env.llvm_branch }}
          files: release/*
